// Mocks generated by Mockito 5.0.9 from annotations
// in flutter_app/test/movie_repository_test.dart.
// Do not manually edit this file.

import 'package:flutter_app/database/fav_movies_dao.dart' as _i3;
import 'package:flutter_app/http/tmdb_api.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TmdbApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTmdbApi extends _i1.Mock implements _i2.TmdbApi {
  MockTmdbApi() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [FavoriteMoviesDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteMoviesDao extends _i1.Mock implements _i3.FavoriteMoviesDao {
  MockFavoriteMoviesDao() {
    _i1.throwOnMissingStub(this);
  }
}
